### ISSUE TITLE
Cocoa.NSWindow.AnimationBehavior.Set raises an exception in 10.6

### ISSUE THREAD

**Issue by declaresub** [macoslib/macoslib#120]
Cocoa.NSWindow.AnimationBehavior.Set calls setAnimationBehavior: , which was added in 10.7.

**Comment by kmaehashi** [comment]
The issue seems resolved in the latest macoslib, so this can be closed I think?

https://github.com/macoslib/macoslib/blob/master/macoslib/Cocoa/NSWindow.rbbas#L1894

**Comment by tempelmann** [comment]
Merged. Thanks for your help!
