### ISSUE TITLE
Directory ending with "." confuses Git on Windows

### ISSUE THREAD

**Issue by kmaehashi** [macoslib/macoslib#177]
When cloning macoslib on Windows, "Misc." directory is not recognized by the Windows Explorer and Xojo, as directory name ending with "." is not supported on Windows.

https://github.com/macoslib/macoslib/tree/master/macoslib/Misc.

Is it acceptable to rename "Misc." to "Misc"?
I can open a pull-request for this if needed.

**Comment by vidalvanbergen** [comment]
That should be fine

**Comment by vidalvanbergen** [comment]
The changes have been merged in.

**Comment by kmaehashi** [comment]
@vidalvanbergen Thanks!
