### ISSUE TITLE
NSClassFromString leaks dependency to Cocoa.framework

### ISSUE THREAD

**Issue by kmaehashi** [macoslib/macoslib#178]
In macoslib, `Cocoa.NSClassFromString` is defined as an external method, which obviously depends on `Cocoa.framework`.
As many classes in macoslib (e.g. `NSApplication.ClassRef`) call `NSClassFromString` without `#ifdef TargetMacOS` block, this will cause Runtime Error (`Failed to load library Cocoa.framework`) on non-Mac platform.

The minimal example project to reproduce this issue is as follows. This project runs on Mac, but shows "Runtime Error" on Windows:
https://gist.github.com/kmaehashi/e0504d506774b38daf35

I have two ideas:

1. Change `NSClassFromString` to a shared method, and use `Declare` inside `#ifdef TargetMacOS` block in the method.
2. Use `#ifdef TargetMacOS` block for everywhere using `NSClassFromString`.

I think 1. is better.  How do you think?

**Comment by kmaehashi** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/939877/6331525/03b5a03c-bbc3-11e4-8d0e-2b74eb267904.png)

**Comment by tempelmann** [comment]
I think solution 1 is the better one. If you make the change, along with updating the Version and the History text, I'm happy to merge it quickly.

**Comment by kmaehashi** [comment]
Thanks, I'll send a pull-req later.
