### ISSUE TITLE
TypeMismatchException when writing an array preference on Windows

### ISSUE THREAD

**Issue by khagler** [macoslib/macoslib#191]
Here's code to reproduce the problem:

    Dim prefs As New TTsSmartPreferences("Testing")
    Dim defaultPref() As String
    defaultPref = Array("foo", "bar")
    prefs.Value("somearray") = defaultPref
    prefs.Sync    

When this is run on Windows 7, I get a `TypeMismatchException` in `XMLDictionary.StorageCount`. The highlighted line in the debugger is:

    dim a() as Variant = storage
    
At this point, storage is a `String` array, and unfortunately Xojo isn't capable of going from an array of anything else to an array of variants unless you don't want it to (the parameter to `StorageCount` is `storage As Variant`). For this to work, storage has to be converted (back) into an array of variants before it's assigned to `a`.

**Comment by tempelmann** [comment]
I've worked on this for an hour and have given up. Xojo simply makes this too difficult. You'll have to keep using Variants for arrays to make this work, I cannot get this working fully automatically inside the XmlDictionary, sadly.

**Comment by khagler** [comment]
For what it's worth, I updated macoslib in my project after seeing that your pull request had been merged, and now instead of the original problem, I'm getting a framework failed assertion--Feedback ID 40350.

**Comment by khagler** [comment]
I spent more time beating my head against this particular wall. Unfortunately there's no workaround--Xojo's Variant type is simply broken with arrays, making it impossible to store arrays with TTsSmartPreferences.
