### ISSUE TITLE
🚫 Do NOT Download/Use This Software

### ISSUE THREAD

**Issue by JMichaelTX** [macoslib/macoslib#206]
It has NOT been maintained and does NOT even have the current Xojo extension.
It fails to compile and run properly.

I think it has been abandoned.

**Comment by vidalvanbergen** [comment]
Please try this fork, which has been updated for 64bit and compiles just fine using the current latest public version of Xojo.

https://github.com/vidalvanbergen/macoslib

(The file extension hasn't been changed for backwards compatibility.)

**Comment by tempelmann** [comment]
Please understand the difference between downloading and using. There is no harm in downloading it. You make it sound like it's a virus.

**Comment by vidalvanbergen** [comment]
Unfortunately I don't have write access to this project. I've updated the README.md at my own fork to indicate that the 'master' branch is now the 64bit version and made a separate branch for 32bit and backwards compatibility.

I've also made sure that macoslib compiles and runs in the latest release of Xojo (2020R2.1 as of this writing.) and on both Intel and ARM.

**Comment by declaresub** [comment]
@vidalvanbergen You should now have committer access.

**Comment by vidalvanbergen** [comment]
Thank you! I'll try my best to maintain macoslib. ;)
